name: trast
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterThin.ttf
          weight: 100
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoItalicThin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRegular.ttf
          weight: 400
